name: sync-gitee-mirror

on: [ push, delete, create ]

concurrency:
  group: git-mirror

jobs:
  git-mirror:
    if: github.repository_owner == 'ChiahsinChu'
    runs-on: ubuntu-latest
    steps:
      - uses: abersheeran/sync-gitee-mirror@v1-beta
        with:
          repository: ChiahsinChu/toolbox
          username: ${{ secrets.GITTE_USERNAME }}
          password: ${{ secrets.GITEE_PASSWORD }}
