name: sync-gitee-mirror

on: [ push, delete, create ]

concurrency:
  group: git-mirror

jobs:
  git-mirror:
    if: github.repository_owner == 'ChiahsinChu'
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SYNC_GITEE_PRIVATE_KEY }}
        with:
          source-repo: "git@github.com:ChiahsinChu/toolbox.git"
          destination-repo: "git@gitee.com:chiahsinchu/toolbox.git"
